### ISSUE TITLE
[JNPCT Adolescent]: Checklist: For QA & BA

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#29]
- [x] Visit Schedule Logics
- [x] Over all App flow
- [x] User Permissions
- [x] Translations (Gujarati)
- [x] Disable UAT Users
