### ISSUE TITLE
[JNPCT Adolescent: Batch 1: Upload bundle for feedback shared by client to production.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#61]
- [x] [[JNPCT Adolescent]: Changes in child followup form.#57](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/jnpct-adolescent/57)

- [x] [[JNPCT Adolescent]: Rename the Child to Adolescent from the entire app.#58](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/jnpct-adolescent/58)

- [x] [[JNPCT Adolescent]: Edit Access for child followup form for supervisor and cluster incharge.#59](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/jnpct-adolescent/59)

- [x] [[JNPCT Adolescent]: "Number of family members" and "Mother's Education" question in Individual Registration should be non-mandatory.#56](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/jnpct-adolescent/56)

- [x] [[JNPCT Adolescent]: Update user and catchment as per new changes.#60](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/jnpct-adolescent/60)

**Comment by Dinesh2019** [comment]
- [x] When we cancel the visit the subsequent visit is not scheduled.
